<?php

return [

  // id1
  [
    'restaurant_id' => 1,
    'name' => 'Topinambur arrosto',
    'description' => 'Topinambur cotto a bassa temperatura e scottato a fiamma viva, crema di mandorle al limone',
    'price' => 13 ,
    'available' => true,
    'image' => 'https://mangiarebene.s3.amazonaws.com/uploads/recipe/image/7170/mb_asset.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => 'insalata di patate alla berlinese',
    'description' => 'Insalata di patate alla berlinese con scarola ripassata',
    'price' => 12 ,
    'available' => true,
    'image' => 'https://media-assets.lacucinaitaliana.it/photos/61fd2d9abb11247c6ce40bc7/1:1/w_2560%2Cc_limit/Insalata-di-patate-alla-tedesca.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => 'Tagliolino burro e alici',
    'description' => 'Tagliolino al burro e alga nori con olive taggiasche e pomodori secchi',
    'price' => 14 ,
    'available' => true,
    'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/04/Spaghetti-burro-e-alici-foto-finale-.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => 'Pasta alla norma',
    'description' => 'Pasta con sugo di melanzane e ricotta salata',
    'price' => 13 ,
    'available' => true,
    'image' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/12/ricetta-pasta-norma/_jcr_content/header-par/image_single.img.jpg/1562754500727.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => "Rigatoni all'amatriciana ",
    'description' => 'Rigatoni con sugo, guanciale e pecorino romano',
    'price' => 11 ,
    'available' => true,
    'image' => 'https://mutti-parma.com/app/uploads/sites/7/2019/09/thumb-1223-recipe-cover-desktop-800x450.jpeg',
  ],
  [
    'restaurant_id' => 1,
    'name' => "l'insalata si è scottata",
    'description' => 'Insalata fermentata e cotta a bassa temperatura, con verdure di stagione scottate e crumble di noci',
    'price' => 15 ,
    'available' => true,
    'image' => 'https://www.gustosano.eu/wp-content/uploads/2014/07/insalata-di-lattuga-scottata.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => 'Polpette di melanzane',
    'description' => 'Polpette di melanzane con yogurt e menta fresca',
    'price' => 13 ,
    'available' => true,
    'image' => 'https://cdn.cook.stbm.it/thumbnails/ricette/42/42477/hd750x421.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => "Sedanop rapa glassato",
    'description' => 'Sedano rapa glassato e cotto a bassa temperatura con insalatina orientale',
    'price' => 14 ,
    'available' => true,
    'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/03/12-arrosto-di-sedano-rapa-servire__MG_1218.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => 'Acqua',
    'description' => 'Acqua Naturale',
    'price' => 2 ,
    'available' => true,
    'image' => 'https://topdrinksdistribuzione.it/shop/511-large_default/acqua-san-benedetto-naturale-in-vetro-a-rendere-1-lt-x-12-bt.jpg',
  ],
  [
    'restaurant_id' => 1,
    'name' => 'Vino Rosso',
    'description' => 'Vino rosso della casa, con aromi fruttati',
    'price' => 12 ,
    'available' => true,
    'image' => 'https://www.my-personaltrainer.it/2022/08/24/vino-rosso-orig.jpeg',
  ],

  // id2
  [
    'restaurant_id' => 2,
    'name' => "Polpo All'insalata",
    'description' => 'Con schiacciata di patate al profumo di limone',
    'price' => 16 ,
    'available' => true,
    'image' => 'https://www.antoniettapolcaro.it/wp-content/uploads/2022/12/ricette-di-natale-8-idee-antipasti-insalata-polpo.jpg',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Ricotta di bufala alle Noci",
    'description' => 'Con cipollina carammellata e miele',
    'price' => 12 ,
    'available' => true,
    'image' => 'https://www.caseificiolastellabianca.com/wp-content/uploads/2020/05/ricotta_cuori_noci.jpg',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Margherita",
    'description' => "pomodoro, mozzarella, basilico e olio extravergine d'oliva",
    'price' => 7,
    'available' => true,
    'image' => 'https://it.ooni.com/cdn/shop/articles/Margherita-9920.jpg?crop=center&height=800&v=1644590028&width=800',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Marinara",
    'description' => "pomodoro, origano, aglio e olio extravergine d'oliva",
    'price' => 7,
    'available' => true,
    'image' => 'https://it.ooni.com/cdn/shop/articles/marinara-for-web.jpg?crop=center&height=800&v=1635275961&width=800',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Quattro Stagioni",
    'description' => "pomodoro, carciofini, mozzarella fiordilatte, prosciutto cotto, salame, funghi, basilico e olio extravergine d'oliva",
    'price' => 9,
    'available' => true,
    'image' => 'https://primochef.it/wp-content/uploads/2020/04/SH_pizza_quattro_stagioni.jpg',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Caprese",
    'description' => "ombra di pomodoro, mozzarella fiordilatte, pomodorini, basilico, formaggio e olio extravergine d'oliva",
    'price' => 9,
    'available' => true,
    'image' => 'https://www.gozney.com/cdn/shop/articles/Caprese_Pizza_Feng_Chen_leopardcrust_-_Large_b45ed4e9-09f8-4bad-a6e9-f2391392a2a0.jpg?v=1653033792',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Mezzanelli alla Genovese",
    'description' => "ragù bianco a base di cipolla e carne di manzo",
    'price' => 14,
    'available' => true,
    'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/02/pasta-genovese-still-life-1200x675.jpg',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Spaghettone alle Vongole",
    'description' => "con friarielli e tarallo napoletano",
    'price' => 18,
    'available' => true,
    'image' => 'https://www.cucchiaio.it/content/dam/cucchiaio/it/ricette/2017/01/spaghetti-vongole/spaghetti-alle-vongole-ante.jpg',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Tagliata di Manzo",
    'description' => "con rucola, scaglie di grana, aceto balsamico e pomodorini",
    'price' => 24,
    'available' => true,
    'image' => 'https://thehappyfoodie.co.uk/wp-content/uploads/2021/08/my_simple_italian_1_43_img_s900x0_c2038x1192_l0x856.jpg',
  ],
  [
    'restaurant_id' => 2,
    'name' => "Polpettine al Ragù Napoletano",
    'description' => "Polpettine al Ragù Napoletano con patate saltate",
    'price' => 16,
    'available' => true,
    'image' => 'https://macelleria.scelteperte.it/wp-content/uploads/2022/02/polpette-fritte-napoletane.jpg',
  ],

  // id3
  [
    'restaurant_id' => 3,
    'name' => "Tagliere misto salumi",
    'description' => 'Il tagliere misto di salumi pregiati da produzioni artigianali (consigliato per 2 pax)',
    'price' =>  23,
    'available' => true,
    'image' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2022/12/IDEA_DI_TAGLIERE_DI_SALUMI_E_FORMAGGI_PER_MILLE_OCCASIONI_SITO-4.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Midollo alla brace",
    'description' => 'Il Midollo alla brace aromatizzato ',
    'price' =>  13,
    'available' => true,
    'image' => 'https://media-cdn.tripadvisor.com/media/photo-s/1b/ff/0c/a4/midollo-alla-brace.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "tartare classica",
    'description' => 'Classica: olio, sale e pepe',
    'price' =>  18,
    'available' => true,
    'image' => 'https://primochef.it/wp-content/uploads/2018/04/SH_Tartare_manzo.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Tartare di manzao al Tartufo",
    'description' => 'Crema al tartufo e tuorlo d’uovo ',
    'price' =>  20,
    'available' => true,
    'image' => 'https://agritaste.com/wp-content/uploads/2022/03/iStock-1283518019-tartare-bianco.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Bigoli caio e pepe",
    'description' => 'I Bigoli Cacio & Pepe ',
    'price' =>  16,
    'available' => true,
    'image' => 'https://media-cdn.tripadvisor.com/media/photo-s/10/86/b2/b6/bigoli-cacio-e-pepe-alla.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Tagliatelle al tartufo",
    'description' => 'Le Tagliatelle con Crema di Tartufo Nero e Parmigiano',
    'price' =>  20,
    'available' => true,
    'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/11/tagliatelle-al-tartufo.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Filetto",
    'description' => 'Il FILETTO mignon al Pepe Nero e Senape Antica',
    'price' =>  30,
    'available' => true,
    'image' => 'https://www.giallozafferano.it/images/184-18454/Filetto-al-pepe-verde_650x433_wm.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Filetto",
    'description' => 'Il FILETTO mignon al Gorgonzola e Noci',
    'price' =>  30,
    'available' => true,
    'image' => 'https://www.igorgorgonzola.com/sistemaNews/newsFoto/videoricette/ricetta-tagliata-con-crema-al-gorgonzola.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Filetto",
    'description' => 'Il FILETTO mignon alla crema di Tartufo e Parmigiano ',
    'price' =>  32,
    'available' => true,
    'image' => 'https://www.chefstefanobarbato.com/ita/wp-content/uploads/2020/11/Filetto-al-Tartufo-Bianco-pres.jpg',
  ],
  [
    'restaurant_id' => 3,
    'name' => "Patate al forno",
    'description' => 'Patate al forno con rosmarino e aglio',
    'price' =>  6,
    'available' => true,
    'image' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2015/04/patate-al-forno/_jcr_content/header-par/image-single.img.jpg/1581958003248.jpg',
  ],

  // id4
];