<?php

return [
  [
    'user_id' => '1',
    'restaurant_name' => 'Solo Crudo',
    'restaurant_email' => 'info@solocrudo.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/1a/55/81/4f/solo-crudo-raw-food-gentle.jpg',
    'restaurant_logo' => 'https://www.ioscelgoveg.it/wp-content/uploads/2017/05/solo-crudo.jpg',
    'restaurant_address' => 'Via Vincenzo Viviani, 2, 20124, Milano',
  ],
  [
    'user_id' => '2',
    'restaurant_name' => 'Napoli 1820',
    'restaurant_email' => 'info@napoli1820.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/19/5c/d8/6d/pizza-vista-naviglio.jpg',
    'restaurant_logo' => 'https://www.napoli1820.com/wp-content/uploads/2022/04/logo.svg',
    'restaurant_address' => 'Alzaia Naviglio Grande, 62, 20144 Milano',
  ],
  [
    'user_id' => '3',
    'restaurant_name' => 'Nero 9',
    'restaurant_email' => 'info@Nero9.com',
    'restaurant_image' => 'https://www.nero9milano.com/wp-content/uploads/2022/11/nero9@SimonaBrunoPh-6.jpg',
    'restaurant_logo' => 'https://www.nero9milano.com/wp-content/themes/nero9-theme-wp/assets/images/logo.png',
    'restaurant_address' => 'Via anfiteatro, 9, 20121 Milano',
  ],
  [
    'user_id' => '4',
    'restaurant_name' => 'Mekan Kebap',
    'restaurant_email' => 'info@mekankebap.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/11/2e/f8/b8/photo0jpg.jpg',
    'restaurant_logo' => 'https://img.freepik.com/premium-vector/kebab-logo-vector-illustration_518759-211.jpg',
    'restaurant_address' => 'Via Carlo Troya 10 Piazza Baiamonti, 2, 20154 Milano',
  ],
  [
    'user_id' => '5',
    'restaurant_name' => 'Kandoo Restaurant',
    'restaurant_email' => 'info@kandoorestaurant.it',
    'restaurant_image' => 'https://kandoosushimilano.it/wp-content/uploads/2020/06/RISTO02-1024x646.jpg',
    'restaurant_logo' => 'https://kandoosushimilano.it/wp-content/uploads/2021/06/logo.svg',
    'restaurant_address' => 'Viale Corsica, 38, 20137, Milano',
  ],
  [
    'user_id' => '6',
    'restaurant_name' => 'Carmelina',
    'restaurant_email' => 'info@carmelina.com',
    'restaurant_image' => 'https://zero-media.s3.amazonaws.com/uploads/2019/11/carmelina-e1574097965108.jpg',
    'restaurant_logo' => 'https://locandacarmelina.com/wp-content/uploads/2023/01/elemento-header.svg',
    'restaurant_address' => 'Via Genova Thaon di Revel, 5, 20159 Milano',
  ],
  [
    'user_id' => '7',
    'restaurant_name' => 'Ristorante Indiano Just India',
    'restaurant_email' => 'info@justIndia.it',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/17/fe/65/19/photo1jpg.jpg',
    'restaurant_logo' => 'https://img.freepik.com/premium-vector/indian-restaurant-logo-design-inspiration_57043-225.jpg',
    'restaurant_address' => 'Via B. Marcello, 34, 20124 Milano',
  ],
  [
    'user_id' => '8',
    'restaurant_name' => 'Vanilla Gelati Italiani',
    'restaurant_email' => 'info@vanillagelati.com',
    'restaurant_image' => 'https://vanilla-gelati-italiani.it/wp-content/uploads/2022/03/Vanilla-1-scaled.jpg',
    'restaurant_logo' => 'https://vanilla-gelati-italiani.it/wp-content/uploads/2022/03/logo-vanilla-3.png',
    'restaurant_address' => 'Via Pattari, 2, 20122 Milano',
  ],
  [
    'user_id' => '9',
    'restaurant_name' => 'Osteria del Gambero Rosso',
    'restaurant_email' => 'info@osteriadelgamberorosso.it',
    'restaurant_image' => 'https://www.algambero.com/wp-content/uploads/2013/03/slide_home_01.jpg',
    'restaurant_logo' => 'https://www.algambero.com/wp-content/uploads/2013/02/logo_header.jpg',
    'restaurant_address' => 'Viale Pasubio, 6, 20154, Milano',
  ],
  [
    'user_id' => '10',
    'restaurant_name' => 'Burger Trip"',
    'restaurant_email' => 'info@burgerTrip.com',
    'restaurant_image' => 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/7eac964e-82d9-4478-a7eb-e4f991ed6231/57df9c14-9f4d-4c53-a33f-1b9084dfa926.jpg',
    'restaurant_logo' => 'https://cdn.website.dish.co/media/28/16/6312003/BURGER-TRIP-LOGO-BURGERCoTRIP-BIANCO-png.jpg',
    'restaurant_address' => 'Via Giannetto Mattei, 62 Le Mimose, 20044 Milano',
  ],
  [
    'user_id' => '11',
    'restaurant_name' => 'Fei Yun Ge',
    'restaurant_email' => 'info@feiyunge.it',
    'restaurant_image' => 'https://www.ristorantefeiyunge.it/wp-content/uploads/2021/12/244335_FeiYunGe_Hero.jpg',
    'restaurant_logo' => 'https://www.ristorantefeiyunge.it/wp-content/uploads/2021/10/vetro3-scaled.jpg',
    'restaurant_address' => 'Via Melchiorre Gioia, 141, 20125, Milano',
  ],
  [
    'user_id' => '12',
    'restaurant_name' => 'Bar Pasticceria Rovida',
    'restaurant_email' => 'info@barpasticceriarovida.it',
    'restaurant_image' => 'https://le-strade.com/wp-content/uploads/2020/07/004LestradediMilano_Pasticceria_Rovida.jpg',
    'restaurant_logo' => 'https://www.pasticceriarovida.it/wp-content/uploads/2022/07/Rovida-logo.jpeg',
    'restaurant_address' => 'Via Domenico Scarlatti, 21, 20124 Milano',
  ],
];