<?php

return [
  [
    'user_id' => '1',
    'restaurant_name' => 'Solo Crudo',
    'restaurant_email' => 'info@solocrudo.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/1a/55/81/4f/solo-crudo-raw-food-gentle.jpg',
    'restaurant_logo' => 'https://www.ioscelgoveg.it/wp-content/uploads/2017/05/solo-crudo.jpg',
    'restaurant_address' => 'Via Vincenzo Viviani, 2, 20124, Milano',
  ],
  [
    'user_id' => '2',
    'restaurant_name' => 'Napoli 1820',
    'restaurant_email' => 'info@napoli1820.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/19/5c/d8/6d/pizza-vista-naviglio.jpg',
    'restaurant_logo' => 'https://www.napoli1820.com/wp-content/uploads/2022/04/logo.svg',
    'restaurant_address' => 'Alzaia Naviglio Grande, 62, 20144 Milano',
  ],
  [
    'user_id' => '3',
    'restaurant_name' => 'Nero 9',
    'restaurant_email' => 'info@Nero9.com',
    'restaurant_image' => 'https://www.nero9milano.com/wp-content/uploads/2022/11/nero9@SimonaBrunoPh-6.jpg',
    'restaurant_logo' => 'https://www.nero9milano.com/wp-content/themes/nero9-theme-wp/assets/images/logo.png',
    'restaurant_address' => 'Via anfiteatro, 9, 20121 Milano',
  ],
  [
    'user_id' => '4',
    'restaurant_name' => 'Mekan Kebap',
    'restaurant_email' => 'info@mekankebap.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/11/2e/f8/b8/photo0jpg.jpg',
    'restaurant_logo' => 'https://img.freepik.com/premium-vector/kebab-logo-vector-illustration_518759-211.jpg',
    'restaurant_address' => 'Via Carlo Troya 10 Piazza Baiamonti, 2, 20154 Milano',
  ],
  [
    'user_id' => '5',
    'restaurant_name' => 'Kandoo Restaurant',
    'restaurant_email' => 'info@kandoorestaurant.it',
    'restaurant_image' => 'https://kandoosushimilano.it/wp-content/uploads/2020/06/RISTO02-1024x646.jpg',
    'restaurant_logo' => 'https://kandoosushimilano.it/wp-content/uploads/2021/06/logo.svg',
    'restaurant_address' => 'Viale Corsica, 38, 20137, Milano',
  ],
  [
    'user_id' => '6',
    'restaurant_name' => 'Carmelina',
    'restaurant_email' => 'info@carmelina.com',
    'restaurant_image' => 'https://zero-media.s3.amazonaws.com/uploads/2019/11/carmelina-e1574097965108.jpg',
    'restaurant_logo' => 'https://locandacarmelina.com/wp-content/uploads/2023/01/elemento-header.svg',
    'restaurant_address' => 'Via Genova Thaon di Revel, 5, 20159 Milano',
  ],
  [
    'user_id' => '7',
    'restaurant_name' => 'Ristorante Indiano Just India',
    'restaurant_email' => 'info@justIndia.it',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/17/fe/65/19/photo1jpg.jpg',
    'restaurant_logo' => 'https://img.freepik.com/premium-vector/indian-restaurant-logo-design-inspiration_57043-225.jpg',
    'restaurant_address' => 'Via B. Marcello, 34, 20124 Milano',
  ],
  [
    'user_id' => '8',
    'restaurant_name' => 'Vanilla Gelati Italiani',
    'restaurant_email' => 'info@vanillagelati.com',
    'restaurant_image' => 'https://vanilla-gelati-italiani.it/wp-content/uploads/2022/03/Vanilla-1-scaled.jpg',
    'restaurant_logo' => 'https://vanilla-gelati-italiani.it/wp-content/uploads/2022/03/logo-vanilla-3.png',
    'restaurant_address' => 'Via Pattari, 2, 20122 Milano',
  ],
  [
    'user_id' => '9',
    'restaurant_name' => 'Osteria del Gambero Rosso',
    'restaurant_email' => 'info@osteriadelgamberorosso.it',
    'restaurant_image' => 'https://www.algambero.com/wp-content/uploads/2013/03/slide_home_01.jpg',
    'restaurant_logo' => 'https://www.algambero.com/wp-content/uploads/2013/02/logo_header.jpg',
    'restaurant_address' => 'Viale Pasubio, 6, 20154, Milano',
  ],
  [
    'user_id' => '10',
    'restaurant_name' => 'Burger Trip"',
    'restaurant_email' => 'info@burgerTrip.com',
    'restaurant_image' => 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/7eac964e-82d9-4478-a7eb-e4f991ed6231/57df9c14-9f4d-4c53-a33f-1b9084dfa926.jpg',
    'restaurant_logo' => 'https://cdn.website.dish.co/media/28/16/6312003/BURGER-TRIP-LOGO-BURGERCoTRIP-BIANCO-png.jpg',
    'restaurant_address' => 'Via Giannetto Mattei, 62 Le Mimose, 20044 Milano',
  ],
  [
    'user_id' => '11',
    'restaurant_name' => 'Fei Yun Ge',
    'restaurant_email' => 'info@feiyunge.it',
    'restaurant_image' => 'https://www.ristorantefeiyunge.it/wp-content/uploads/2021/12/244335_FeiYunGe_Hero.jpg',
    'restaurant_logo' => 'https://www.ristorantefeiyunge.it/wp-content/uploads/2021/10/vetro3-scaled.jpg',
    'restaurant_address' => 'Via Melchiorre Gioia, 141, 20125, Milano',
  ],
  [
    'user_id' => '12',
    'restaurant_name' => 'Bar Pasticceria Rovida',
    'restaurant_email' => 'info@barpasticceriarovida.it',
    'restaurant_image' => 'https://le-strade.com/wp-content/uploads/2020/07/004LestradediMilano_Pasticceria_Rovida.jpg',
    'restaurant_logo' => 'https://www.pasticceriarovida.it/wp-content/uploads/2022/07/Rovida-logo.jpeg',
    'restaurant_address' => 'Via Domenico Scarlatti, 21, 20124 Milano',
  ],
  [
    'user_id' => '13',
    'restaurant_name' => 'Cantiere Hambirreria',
    'restaurant_email' => 'info@hambirreria.com',
    'restaurant_image' => 'https://www.mangiaebevi.it/wp-content/uploads/2017/06/01-Hambirreria.jpg',
    'restaurant_logo' => 'https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/9f/d3/41/9fd341c7-6e7d-2a1d-b2b9-77b9b134cb3b/source/512x512bb.jpg',
    'restaurant_address' => 'Via Vincenzo Viviani, 2, 20124, Milano',
  ],
  [
    'user_id' => '14',
    'restaurant_name' => 'Crotto Quartino',
    'restaurant_email' => 'info@crotto.com',
    'restaurant_image' => 'https://www.scattidigusto.it/wp-content/uploads/2022/07/Crotto-Quartino-Milano-1280x853.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGWK_dZIbHbSzhs4U3_Zow1MTgQVidhqd3xAJwltszCMHYDrZg5mVXBffIwiWz8I0CjP4&usqp=CAU',
    'restaurant_address' => 'Alzaia Naviglio Grande, 62, 20144 Milano',
  ],
  [
    'user_id' => '15',
    'restaurant_name' => 'Maccheroni',
    'restaurant_email' => 'info@maccheroni.com',
    'restaurant_image' => 'https://www.gazzettadimilano.it/wp-content/uploads/2021/11/Maccheroni_ristorante-interno_03.jpg',
    'restaurant_logo' => 'https://maccheronicucinaitaliana.com/wp-content/uploads/2022/12/Nuovo-Logo-Maccheroni-1200-628-1024x536.png',
    'restaurant_address' => 'Via anfiteatro, 9, 20121 Milano',
  ],
  [
    'user_id' => '16',
    'restaurant_name' => 'Bottega Sicula Pescheria',
    'restaurant_email' => 'info@bottegasicula.com',
    'restaurant_image' => 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/39e59333-0152-4f48-90f1-c210a63e524e/70a143e1-1bb2-4248-960c-0483bd9c89f9.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQyHBAzxrzmN2MegqCODg7PaHTI7fyIN_H4U1qIxbYOA&s',
    'restaurant_address' => 'Via Carlo Troya 10 Piazza Baiamonti, 2, 20154 Milano',
  ],
  [
    'user_id' => '17',
    'restaurant_name' => 'Sushi Fratelli Milano',
    'restaurant_email' => 'info@fratellisushi.it',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/2a/86/15/70/nuovo-ristrutturato.jpg',
    'restaurant_logo' => 'https://fratellisushi.it/images/logo.png',
    'restaurant_address' => 'Viale Corsica, 38, 20137, Milano',
  ],
  [
    'user_id' => '18',
    'restaurant_name' => 'Eataly Milano Smeraldo',
    'restaurant_email' => 'info@eataly.com',
    'restaurant_image' => 'https://www.lucianopignataro.it/wp-content/uploads/2020/10/Pizze-d%E2%80%99Italia-in-festa.png',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLDgNXWfVvjw8KV3kYM0tAT8WGP9IVAmIo76qvLLdsxaMaGYzOZQlz3ZVRvJidp95Ra0Q&usqp=CAU',
    'restaurant_address' => 'Via Genova Thaon di Revel, 5, 20159 Milano',
  ],
  [
    'user_id' => '19',
    'restaurant_name' => 'Al Cantinone',
    'restaurant_email' => 'info@cantinone.it',
    'restaurant_image' => 'https://qul.imgix.net/3ad9f37b-4c2c-4ede-890a-b9f4bb45d88a/591622_sld.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaFKcRuiG_Dsz3tUaSX5aT03U5z2qTIjLczJIkSncZkg&s',
    'restaurant_address' => 'Via B. Marcello, 34, 20124 Milano',
  ],
  [
    'user_id' => '20',
    'restaurant_name' => 'Volemose Bene',
    'restaurant_email' => 'info@volemosebene.com',
    'restaurant_image' => 'https://www.nuovaopinione.it/img/vetrina/127228/6fc262a5-ee15-420b-b257-8d4f2a9545a1.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTEdnwGUKUz2A6UPbsmT6iX3YzNbw-uF92xnKh5nkC3uMdv5in9OPKcwwUv1wqBe9UOuI&usqp=CAU',
    'restaurant_address' => 'Via Pattari, 2, 20122 Milano',
  ],
  [
    'user_id' => '21',
    'restaurant_name' => 'La Rava e la Fava',
    'restaurant_email' => 'info@laravaelafava.it',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/1b/56/0a/c4/dehor.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcex9ebJy9rSFHrAY0lPXrY-Cv1SvChuiSXZPz3mdQsQ&s',
    'restaurant_address' => 'Viale Pasubio, 6, 20154, Milano',
  ],
  [
    'user_id' => '22',
    'restaurant_name' => 'MU Dimsum',
    'restaurant_email' => 'info@mudimsum.com',
    'restaurant_image' => 'https://flawless.life/wp-content/uploads/2019/06/mu-dimsum-interni.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHv65vzhM6wTH6qKzZHN1Y59zqyqFnCUzkN-yois9qgg&s',
    'restaurant_address' => 'Via Giannetto Mattei, 62 Le Mimose, 20044 Milano',
  ],
  [
    'user_id' => '23',
    'restaurant_name' => 'Oren',
    'restaurant_email' => 'info@oren.it',
    'restaurant_image' => 'https://www.oren.it/wp-content/uploads/2018/07/DSC8639.jpg',
    'restaurant_logo' => 'https://www.oren.it/wp-content/uploads/2020/05/OREN-LOGO-2020-WHITE.png',
    'restaurant_address' => 'Via Melchiorre Gioia, 141, 20125, Milano',
  ],
  [
    'user_id' => '24',
    'restaurant_name' => 'Dawat - Indian Restaurant',
    'restaurant_email' => 'info@dawat.it',
    'restaurant_image' => 'https://qul.imgix.net/90063969-7208-4650-8c68-e5ec2896a090/23623_sld.jpg?auto=format&ch=Viewport-Width%2CWidth%2CDPR',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPU3JjFMoiamntZF3euiKOP3yVwoUSSOc6lhFvcUA5eg&s',
    'restaurant_address' => 'Via Domenico Scarlatti, 21, 20124 Milano',
  ],
  [
    'user_id' => '25',
    'restaurant_name' => 'Indo Ceylon',
    'restaurant_email' => 'info@celyon.com',
    'restaurant_image' => 'https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1200,h_630,d_it:cuisines:indiano-8.jpg/v1/it/restaurants/251808.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQA6e2dpOdBTx7weC2uBNM0hfE0RbPHAlTTCoLLiJcAvtIr2mDFaLyYUjdnYAMJRxLCqI&usqp=CAU',
    'restaurant_address' => 'Via Resegone, 1, 20124, Milano',
  ],
  [
    'user_id' => '26',
    'restaurant_name' => 'Jollibee',
    'restaurant_email' => 'info@jollibee.com',
    'restaurant_image' => 'https://vivimilano.corriere.it/wp-content/uploads/2018/04/jollibee-700x467.jpg',
    'restaurant_logo' => 'https://statics.vincom.com.vn/http/vincom-ho/thuong_hieu/anh_logo/Jollibee.png/6ec6dd2b7a0879c9eb1b77a204436a30.webp',
    'restaurant_address' => 'Alzaia Naviglio Grande, 62, 20144 Milano',
  ],
  [
    'user_id' => '27',
    'restaurant_name' => 'Chicken&Chicken',
    'restaurant_email' => 'info@chickenandchicken.com',
    'restaurant_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkHHomLnQYSknpvPc32sO4kFJISDAJXWPOsIlY4ydQILA0Odzjlw-z7IXaPdgC42Nxw3E&usqp=CAU',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXBZAHeQvjk6p8eoCgJyhqYYL6Ts4x_UEcA7ZuMc08isAsYCCiAsY0zfQVeoB6CB0XMUc&usqp=CAU',
    'restaurant_address' => 'Piazza XXIV Maggio, 4, 20121 Milano',
  ],
  [
    'user_id' => '28',
    'restaurant_name' => 'Le Dolci Tradizioni',
    'restaurant_email' => 'info@dolcitradizioni.com',
    'restaurant_image' => 'https://lh5.googleusercontent.com/p/AF1QipNWFyZ6rytfFu-8KV1cq4QxjX-ZTeW88P_WJQsN',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD1XHdipN_jjedP-pi-CFKBG2XyD8DU7s20zaeDKtSAA&s',
    'restaurant_address' => 'Via Carlo Troya 10 Piazza Baiamonti, 2, 20154 Milano',
  ],
  [
    'user_id' => '29',
    'restaurant_name' => 'I Dolci Namura',
    'restaurant_email' => 'info@dolcinamura.it',
    'restaurant_image' => 'https://www.ioscelgoveg.it/wp-content/uploads/2018/09/i-dolci-namura.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRHf7Q3NkHgOZlDIvBFKD8ujI5Um8TUbFBCgcpDbh6NQ&s',
    'restaurant_address' => 'Viale Corsica, 38, 20137, Milano',
  ],
  [
    'user_id' => '30',
    'restaurant_name' => 'Pavè Break',
    'restaurant_email' => 'info@pavebreak.com',
    'restaurant_image' => 'https://lh3.googleusercontent.com/p/AF1QipNmG0qcm-tXnkB0-iKianKN_MD-LXA5sIBW84kT=s1600-w640',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXoPdMMV4prKRNx8kD410bhsqBtS9rJZgLzb2DfnuxR41UGz82FgQkhW0szR-WHoVMYMo&usqp=CAU',
    'restaurant_address' => 'Via Genova Thaon di Revel, 5, 20159 Milano',
  ],
  [
    'user_id' => '31',
    'restaurant_name' => 'Gelateria Dolci Storie',
    'restaurant_email' => 'info@dolcistorie.it',
    'restaurant_image' => 'https://www.foodweb.it/wp-content/uploads/2020/07/ice-cream-2576622_1920.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLcoOY7Dddal7kIqorGLSdr0JEsps3LpOUaB5T3XwhS2a8oRN_eYSywol93gTheB8EhBA&usqp=CAU',
    'restaurant_address' => 'Via B. Marcello, 34, 20124 Milano',
  ],
  [
    'user_id' => '32',
    'restaurant_name' => 'Malìa',
    'restaurant_email' => 'info@malia.com',
    'restaurant_image' => 'https://lh3.googleusercontent.com/p/AF1QipMWmVF_yThjmnMAAKeMisYrsKadv5mOmII4ynbQ=s1600-w640',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQOJ9Jo_CBjEOqaQ-2aCHVs4vF-1dtbEesCNp9RL-5ZRw9d2U4Q_BLjmIpWFXEgAGdsi0&usqp=CAU',
    'restaurant_address' => 'Via Pattari, 2, 20122 Milano',
  ],
  [
    'user_id' => '33',
    'restaurant_name' => 'Al Gambero Rosso',
    'restaurant_email' => 'info@oalgamberorosso.it',
    'restaurant_image' => 'https://www.algambero.com/wp-content/uploads/2013/03/slide_home_01.jpg',
    'restaurant_logo' => 'https://www.algambero.com/wp-content/uploads/2013/02/logo_header.jpg',
    'restaurant_address' => 'Viale Pasubio, 6, 20154, Milano',
  ],
  [
    'user_id' => '34',
    'restaurant_name' => 'Anatolia Doner Kebab',
    'restaurant_email' => 'info@anatoliadoner.com',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/04/35/6f/2b/anatolia-doner-kebab.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVSqMqxW8om3UMlvRj08AnIXY9lujA42yf0qFORJ3hAT9b8VEw_tRTap58ZebPZes3PcM&usqp=CAU',
    'restaurant_address' => 'Via Giannetto Mattei, 62 Le Mimose, 20044 Milano',
  ],
  [
    'user_id' => '35',
    'restaurant_name' => 'Meydan Kebap Pizza Grill',
    'restaurant_email' => 'info@meydankebap.it',
    'restaurant_image' => 'https://meydan-kebap.com/wp-content/uploads/2021/03/IMG_4364-1024x683.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYyNLv77kZeHpKqgJvokRLIcKMtOjOav8645mdCvnU3hvhh7pBwTncbovuxZK37B4buak&usqp=CAU',
    'restaurant_address' => 'Via Melchiorre Gioia, 141, 20125, Milano',
  ],
  [
    'user_id' => '36',
    'restaurant_name' => 'Taglialà',
    'restaurant_email' => 'info@tagliala.it',
    'restaurant_image' => 'https://media-cdn.tripadvisor.com/media/photo-s/1a/dc/3d/56/la-cosa-piu-bella-condividerla.jpg',
    'restaurant_logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzv2ciHbj4Ei7z3IDfV0KxtX945b2hy7wPjM6JKZgxNMMfGSt2M6_-O7iaZNx2uP6Toos&usqp=CAU',
    'restaurant_address' => 'Via Domenico Scarlatti, 21, 20124 Milano',
  ],
];